name       : gstreamer-1.0-plugins-bad
version    : 1.20.3
release    : 82
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.20.3.tar.xz : 7a11c13b55dd1d2386dd902219e41cbfcdda8e1e0aa3e738186c95074b35da4f
homepage   : https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/
license    : LGPL-2.0-or-later
component  :
    - multimedia.gstreamer
    - ^gstreamer-1.0-plugins-opencv : multimedia.gstreamer
    - ^gstreamer-1.0-plugins-opencv-devel : programming.devel
summary    :
    - Additional GStreamer plugins
    - ^gstreamer-1.0-plugins-opencv : OpenCV GStreamer plugins
    - ^gstreamer-1.0-plugins-opencv-devel : Development files for gstreamer-1.0-plugins-opencv
description:
    - GStreamer is a streaming media framework, based on graphs of elements which operate on media data. This package contains plug-ins that aren't tested well enough, or the code is not of good enough quality.
    - ^gstreamer-1.0-plugins-opencv : OpenCV GStreamer plugins
    - ^gstreamer-1.0-plugins-opencv-devel : Development files for gstreamer-1.0-plugins-opencv
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(bluez)
    - pkgconfig(dvdnav)
    - pkgconfig(faad2)
    - pkgconfig(fdk-aac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcurl)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libde265)
    - pkgconfig(libdrm)
    - pkgconfig(libexif)
    - pkgconfig(libmms)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libopenmpt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libwebp)
    - pkgconfig(lilv-0)
    - pkgconfig(libva-drm)
    - pkgconfig(ltc)
    - pkgconfig(microdns)
    - pkgconfig(mjpegtools)
    - pkgconfig(nettle)
    - pkgconfig(nice)
    - pkgconfig(oggkate)
    - pkgconfig(openal)
    - pkgconfig(opencv4)
    - pkgconfig(opus)
    - pkgconfig(orc-0.4)
    - pkgconfig(pango)
    - pkgconfig(sbc)
    - pkgconfig(shaderc)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(srt)
    - pkgconfig(vo-aacenc)
    - pkgconfig(vpx)
    - pkgconfig(wayland-protocols)
    - pkgconfig(webrtc-audio-processing)
    - pkgconfig(x265)
    - pkgconfig(xkbcommon)
    - pkgconfig(zbar)
    - bzip2-devel
    - gsm-devel
    - ladspa-devel
    - vulkan-headers
rundeps    :
    - ^gstreamer-1.0-plugins-opencv-devel :
        - gstreamer-1.0-plugins-opencv
replaces   :
    - gst-transcoder
    - devel : gst-transcoder-devel
setup      : |
    %meson_configure -Dpackage-name="GStreamer Bad Plugins ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dgobject-cast-checks=disabled \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled \
        -Dx11=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
patterns   :
    - ^gstreamer-1.0-plugins-opencv :
        - /usr/lib64/libgstopencv-1.0.so.*
        - /usr/lib64/gstreamer-1.0/libgstopencv.so
    - ^gstreamer-1.0-plugins-opencv-devel :
        - /usr/lib64/libgstopencv-1.0.so
        - /usr/include/gstreamer-1.0/gst/opencv
