name        : gstreamer-1.0-plugins-bad
version     : 1.6.2
release     : 13
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.6.2.tar.xz : 650855e39ff56a8bb6cb0c192109c5926ce12f536d06e19ebf829de71ef396fe
license     :
    - LGPL-2.0
summary     : Additional GStreamer plugins
builddeps   :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libexif)
    - pkgconfig(wayland-client)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(xv)
    - pkgconfig(xvmc)
    - pkgconfig(xxf86vm)
    - pkgconfig(oggkate)
    - pkgconfig(libmpg123)
    - pkgconfig(libass)
    - pkgconfig(libmpeg2)
    - pkgconfig(vpx)
    - pkgconfig(orc-0.4)
    - pkgconfig(dvdread)
    - pkgconfig(dvdnav)
    - pkgconfig(vdpau)
    - pkgconfig(vo-aacenc)
    - pkgconfig(libwebp)
    - pkgconfig(bluez)
    - pkgconfig(opus)
    - libjpeg-turbo-devel
    - faac-devel
    - faad-devel
    - libgcrypt-devel
    - libnettle-devel
description : |
    Additional GStreamer plugins - not considered to be up to par with -good plugins
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Bad Plugins 1.6.2 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
