name       : gstreamer-1.0-plugins-bad
version    : 1.10.4
release    : 27
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.10.4.tar.xz : 23ddae506b3a223b94869a0d3eea3e9a12e847f94d2d0e0b97102ce13ecd6966
license    : LGPL-2.0
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    Additional GStreamer plugins - not considered to be up to par with -good plugins
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libass)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libmpeg2)
    - pkgconfig(libmpg123)
    - pkgconfig(libwebp)
    - pkgconfig(oggkate)
    - pkgconfig(orc-0.4)
    - pkgconfig(vdpau)
    - pkgconfig(vo-aacenc)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(xvmc)
    - pkgconfig(xxf86vm)
    - libjpeg-turbo-devel
    - faac-devel
    - faad-devel
    - libgcrypt-devel
    - libnettle-devel
setup      : |
    %configure --disable-static \
               --with-package-name="GStreamer Bad Plugins 1.10.4 Solus" \
               --with-package-origin="https://solus-project.com"
build      : |
    %make
install    : |
    %make_install
