name       : gstreamer-1.0-plugins-bad
version    : 1.18.1
release    : 64
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.18.1.tar.xz : c195978c85d97406c05eb9d43ac54b9ab35eda6ffdae32b3ed597b8f1743c1b2
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs of elements which operate on media data. This package contains plug-ins that aren't tested well enough, or the code is not of good enough quality.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(bluez)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(fdk-aac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcurl)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libde265)
    - pkgconfig(libdrm)
    - pkgconfig(libexif)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libwebp)
    - pkgconfig(lilv-0)
    - pkgconfig(libva-drm)
    - pkgconfig(mjpegtools)
    - pkgconfig(nettle)
    - pkgconfig(nice)
    - pkgconfig(oggkate)
    - pkgconfig(opus)
    - pkgconfig(orc-0.4)
    - pkgconfig(pango)
    - pkgconfig(sbc)
    - pkgconfig(soundtouch)
    - pkgconfig(vo-aacenc)
    - pkgconfig(vpx)
    - pkgconfig(wayland-protocols)
    - pkgconfig(webrtc-audio-processing)
    - pkgconfig(x265)
    - pkgconfig(xkbcommon)
    - bzip2-devel
    - faad-devel
    - ladspa-devel
    - vulkan-headers
replaces   :
    - gst-transcoder
    - devel: gst-transcoder-devel
setup      : |
    %meson_configure -Dpackage-name="GStreamer Bad Plugins ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dgobject-cast-checks=disabled \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled \
        -Dx11=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
