name       : gstreamer-1.0-plugins-bad
version    : 1.14.4
release    : 46
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.14.4.tar.xz : 910b4e0e2e897e8b6d06767af1779d70057c309f67292f485ff988d087aa0de5
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs of elements which operate on media data. This package contains plug-ins that aren't tested well enough, or the code is not of good enough quality.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(bluez)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(fdk-aac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libass)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libwebp)
    - pkgconfig(mjpegtools)
    - pkgconfig(nettle)
    - pkgconfig(nice)
    - pkgconfig(oggkate)
    - pkgconfig(opus)
    - pkgconfig(orc-0.4)
    - pkgconfig(vdpau)
    - pkgconfig(vo-aacenc)
    - pkgconfig(vpx)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(webrtc-audio-processing)
    - pkgconfig(x265)
    - pkgconfig(xv)
    - pkgconfig(xvmc)
    - pkgconfig(xxf86vm)
    - bzip2-devel
    - faad-devel
setup      : |
    %configure --disable-static \
               --with-gtk=3.0 \
               --enable-experimental \
               --with-package-name="GStreamer Bad Plugins ${version} Solus" \
               --with-package-origin="https://getsol.us"
build      : |
    %make
install    : |
    %make_install
check      : |
    # Some tests are still failing
    %make check || :
