name       : gstreamer-1.0-plugins-bad
version    : 1.16.0
release    : 50
source     :
    - https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.16.0.tar.xz : 22139de35626ada6090bdfa3423b27b7fc15a0198331d25c95e6b12cb1072b05
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Additional GStreamer plugins
description: |
    GStreamer is a streaming media framework, based on graphs of elements which operate on media data. This package contains plug-ins that aren't tested well enough, or the code is not of good enough quality.
builddeps  :
    - pkgconfig(aom)
    - pkgconfig(bluez)
    - pkgconfig(dvdnav)
    - pkgconfig(dvdread)
    - pkgconfig(fdk-aac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libaacs)
    - pkgconfig(libass)
    - pkgconfig(libchromaprint)
    - pkgconfig(libcurl)
    - pkgconfig(libdc1394-2)
    - pkgconfig(libde265)
    - pkgconfig(libexif)
    - pkgconfig(libmms)
    - pkgconfig(libmodplug)
    - pkgconfig(libmpeg2)
    - pkgconfig(libopenjp2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libwebp)
    - pkgconfig(lilv-0)
    - pkgconfig(mjpegtools)
    - pkgconfig(nettle)
    - pkgconfig(nice)
    - pkgconfig(oggkate)
    - pkgconfig(opus)
    - pkgconfig(orc-0.4)
    - pkgconfig(pango)
    - pkgconfig(sbc)
    - pkgconfig(soundtouch)
    - pkgconfig(vdpau)
    - pkgconfig(vo-aacenc)
    - pkgconfig(vpx)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(webrtc-audio-processing)
    - pkgconfig(x265)
    - bzip2-devel
    - faad-devel
    - ladspa-devel
    - vulkan-headers
setup      : |
    %configure --disable-static \
               --with-gtk=3.0 \
               --enable-experimental \
               --with-package-name="GStreamer Bad Plugins ${version} Solus" \
               --with-package-origin="https://getsol.us"
build      : |
    %make
install    : |
    %make_install
check      : |
    # Some tests are still failing
    %make check || :
